name: Main CI

on:
  push:
    branches: "*"
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13, 1.14, 1.15, ^1.16]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Run Tests
      run: go test -v -timeout 300s -cover ./...
    
    - name: Run Benchmarks
      run: go test -timeout 300s -bench=. -benchmem
